services:
  backend:
    command: ./mvnw spring-boot:run
    working_dir: /app
    volumes:
      - ./backend:/app

  pdf-extractor:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    volumes:
      - ./pdf-extractor:/app

  frontend:
    command: npm run dev -- --host
    working_dir: /app
    volumes:
      - ./frontend:/app
