version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: travelbill-postgres
    environment:
      POSTGRES_DB: travelbill
      POSTGRES_USER: travelbill
      POSTGRES_PASSWORD: Lucky@0716
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: travelbill-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
