-- V5__Add_Company_Detail_Fields.sql
ALTER TABLE companies ADD COLUMN IF NOT EXISTS contact_name VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS pin_code VARCHAR(10);
